59 feat make header and sidebar as spa by using fetchapi
yuki-shimoda-crypto/42_ft_transcendence pull request #112
Opened 2024-07-07 12:32 UTC by Yono1112

## コミットの種類

- [ ] feat: 新機能や機能の追加
- [ ] fix: バグの修正
- [ ] docs: ドキュメントの変更
- [ ] style: コードスタイルの調整（ロジックの変更は無し）
- [ ] refactor: バグを修正したり機能を追加せずに、コードをリファクタリング
- [ ] test: テストコードの追加や修正
- [ ] chore: ビルドプロセスやツールの変更
- [ ] other: 上記のいずれにも当てはまらないその他の変更

## このプルリクエストの内容

## 変更による影響

## テスト手順

## スクリーンショット

## その他のノート

2024-07-08 06:20 UTC, sora-grayscale reviewed
チャットがリロードなしだと使えないっぽいです。
jsが読み込まれていなのかもしれません。

2024-07-10 03:17 UTC, sora-grayscale requested changes
need fix

2024-07-10 08:35 UTC, yuki-shimoda-crypto submitted a review, later dismissed

2024-07-11 03:09 UTC, Yono1112 commented
修正したので確認お願いします

2024-07-11 04:06 UTC, yuki-shimoda-crypto submitted a review, later dismissed

2024-07-12 00:31 UTC, Yono1112 commented
profile画面のブロックボタンとフレンドボタンのところで、SPAがうまく走らないので、今修正中です

2024-07-12 12:40 UTC, sora-grayscale approved these changes
ok...? ok! okokokokok!!!!!

2024-07-12 12:48 UTC, yuki-shimoda-crypto approved these changes

2024-07-12 12:49 UTC, merged