[fix]: #51 change SECRET_KEY to be managed in .env file
yuki-shimoda-crypto/42_ft_transcendence pull request #52
Opened 2024-05-22 04:00 UTC by Yono1112

[body]
- setting.pyのSECRET_KEYをハードコードするのではなく、".env"内で管理するように変更しました

[notes]

close #51

## コミットの種類

- [ ] feat: 新機能や機能の追加
- [ x ] fix: バグの修正
- [ ] docs: ドキュメントの変更
- [ ] style: コードスタイルの調整（ロジックの変更は無し）
- [ ] refactor: バグを修正したり機能を追加せずに、コードをリファクタリング
- [ ] test: テストコードの追加や修正
- [ ] chore: ビルドプロセスやツールの変更
- [ ] other: 上記のいずれにも当てはまらないその他の変更

## このプルリクエストの内容

## 変更による影響

## テスト手順

## スクリーンショット

## その他のノート

2024-05-22 04:17 UTC, sora-grayscale submitted a review, later dismissed

2024-05-22 05:40 UTC, yuki-shimoda-crypto commented
[patch.txt](https://github.com/yuki-shimoda-crypto/42_ft_transcendence/files/15398444/patch.txt)
確認後、git apply patch.txtをしてみてください。
mypynodjango-environのstubファイルが見つからないから、無視するしかないかも。

2024-05-22 05:42 UTC, yuki-shimoda-crypto requested changes
django-environのmypyの無視するか、stubの追加かどちらかの変更をよろしくおねがいします。

2024-05-22 05:43 UTC, Yono1112 commented
色々調べたけど、結局別のライブラリ(dotenv)使うようにする。dotenvだとmypy通ると思う。

2024-05-22 07:20 UTC, yuki-shimoda-crypto submitted a review, later dismissed

2024-05-22 07:33 UTC, yuki-shimoda-crypto requested changes
[patch_51-fix-secret-key.txt](https://github.com/yuki-shimoda-crypto/42_ft_transcendence/files/15399549/patch_51-fix-secret-key.txt)
確認してからgit apply patch_51-fix-secret-key.txt
をしてください。
requirements.txtにdotenvが追加されていない影響で、productのほうが起動しなくなっていました。

2024-05-22 08:42 UTC, yuki-shimoda-crypto approved these changes

2024-05-22 09:07 UTC, sora-grayscale approved these changes
:)

2024-05-23 01:16 UTC, rnakaa approved these changes

2024-05-23 01:17 UTC, merged