43 feat create game implement single player mode with cpu
yuki-shimoda-crypto/42_ft_transcendence pull request #62
Opened 2024-06-01 09:14 UTC by yuki-shimoda-crypto

## コミットの種類

- [x ] feat: 新機能や機能の追加
- [ ] fix: バグの修正
- [ ] docs: ドキュメントの変更
- [ ] style: コードスタイルの調整（ロジックの変更は無し）
- [ ] refactor: バグを修正したり機能を追加せずに、コードをリファクタリング
- [ ] test: テストコードの追加や修正
- [ ] chore: ビルドプロセスやツールの変更
- [ ] other: 上記のいずれにも当てはまらないその他の変更

## このプルリクエストの内容
ゲームのシングルプレイのフロントエンドの実装をしました。

## 変更による影響

## テスト手順

## スクリーンショット

## その他のノート

2024-06-02 04:54 UTC, Yono1112 commented
MDNによると、"getElementById()"はDOM操作にあたっては古いやり方らしく、"querySelector()"が新しく推奨されるやり方とのことです。
idを取得したい場合はgetElementById("hoge")ではなく、querySelector("#hoge")のように指定できます。
参照→[アクティブラーニング: 基本的な DOM 操作](https://developer.mozilla.org/ja/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents#%E3%82%A2%E3%82%AF%E3%83%86%E3%82%A3%E3%83%96%E3%83%A9%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0_%E5%9F%BA%E6%9C%AC%E7%9A%84%E3%81%AA_dom_%E6%93%8D%E4%BD%9C)]

2024-06-02 04:56 UTC, Yono1112 reviewed
MDNによると、"getElementById()"はDOM操作にあたっては古いやり方らしく、"querySelector()"が新しく推奨されるやり方とのことです。
idを取得したい場合はgetElementById("hoge")ではなく、querySelector("#hoge")のように指定できます。
参照→[アクティブラーニング: 基本的な DOM 操作](https://developer.mozilla.org/ja/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents#%E3%82%A2%E3%82%AF%E3%83%86%E3%82%A3%E3%83%96%E3%83%A9%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0_%E5%9F%BA%E6%9C%AC%E7%9A%84%E3%81%AA_dom_%E6%93%8D%E4%BD%9C)

2024-06-09 07:40 UTC, Yono1112 approved these changes

2024-06-15 04:06 UTC, rnakaa approved these changes

2024-06-23 05:49 UTC, Yono1112 approved these changes

2024-06-23 06:48 UTC, Yono1112 requested changes
それぞれのクラス、関数にdocstringを追加して下さい

2024-06-23 06:49 UTC, Yono1112 approved these changes

2024-06-23 07:06 UTC, sora-grayscale approved these changes

2024-06-23 10:26 UTC, merged