35 feat send direct message to other users
yuki-shimoda-crypto/42_ft_transcendence pull request #67
Opened 2024-06-18 08:38 UTC by sora-grayscale

## コミットの種類

- [x] feat: 新機能や機能の追加
- [ ] fix: バグの修正
- [ ] docs: ドキュメントの変更
- [ ] style: コードスタイルの調整（ロジックの変更は無し）
- [ ] refactor: バグを修正したり機能を追加せずに、コードをリファクタリング
- [ ] test: テストコードの追加や修正
- [ ] chore: ビルドプロセスやツールの変更
- [ ] other: 上記のいずれにも当てはまらないその他の変更

## このプルリクエストの内容

## 変更による影響

## テスト手順

## スクリーンショット

## その他のノート

2024-06-23 08:42 UTC, Yono1112 commented
ユーザー認証でフレンド機能が必要だったので、こっちで作っちゃって、このブランチにプルリク送ります！

2024-06-28 03:36 UTC, Yono1112 requested changes
- 文字数が多いメッセージだとスタイルが崩れてしまうので、修正お願いしたいです！
<img width="1680" alt="スクリーンショット 2024-06-28 12 29 25" src="https://github.com/yuki-shimoda-crypto/42_ft_transcendence/assets/100353174/190b457d-c7d4-45aa-bba3-b8bfb99a19ed">

2024-06-28 03:36 UTC, Yono1112 commented on PongChat/chat/templates/chat_base.html
'common/base.html'をextendしないのは何か意図があるんでしょうか？

2024-06-28 03:56 UTC, sora-grayscale commented on PongChat/chat/templates/chat/chat.html
> +  <style type="text/tailwindcss">
多分もうない

2024-06-28 03:59 UTC, sora-grayscale commented on PongChat/chat/templates/chat_base.html
特にないっす

2024-06-28 04:28 UTC, sora-grayscale commented
なおしましたー

2024-06-28 05:21 UTC, Yono1112 commented on PongChat/chat/templates/chat_base.html
であれば、chat_base.htmlは削除して、common/base.htmlをextendするように変更して下さい
保守性を上げる目的

2024-06-28 05:23 UTC, Yono1112 requested changes
であれば、chat_base.htmlは削除して、common/base.htmlをextendするように変更して下さい
保守性を上げる目的

2024-06-29 04:14 UTC, Yono1112 approved these changes

2024-07-03 10:49 UTC, merged