83 feat top page
yuki-shimoda-crypto/42_ft_transcendence pull request #84
Opened 2024-07-01 02:20 UTC by sora-grayscale

## コミットの種類

- [x] feat: 新機能や機能の追加
- [ ] fix: バグの修正
- [ ] docs: ドキュメントの変更
- [ ] style: コードスタイルの調整（ロジックの変更は無し）
- [ ] refactor: バグを修正したり機能を追加せずに、コードをリファクタリング
- [ ] test: テストコードの追加や修正
- [ ] chore: ビルドプロセスやツールの変更
- [ ] other: 上記のいずれにも当てはまらないその他の変更

## このプルリクエストの内容
- top pageを作りました

## 変更による影響

## テスト手順

## スクリーンショット

## その他のノート

2024-07-01 13:44 UTC, Yono1112 submitted a review, later dismissed
良さそう！

2024-07-03 07:02 UTC, yuki-shimoda-crypto requested changes

2024-07-03 07:04 UTC, yuki-shimoda-crypto requested changes
コメントを見てみてください。

2024-07-03 07:13 UTC, sora-grayscale commented on PongChat/pingpong/routing.py
> +    path("ws/chatroom/<chatroom_name>", ChatroomConsumer.as_asgi()),
２ファイルに分けて書く方法がわからなかったっす

2024-07-03 07:14 UTC, sora-grayscale commented on PongChat/PongChat/asgi.py
>  )
これでdaphne動きました？

2024-07-03 07:15 UTC, sora-grayscale commented on PongChat/PongChat/settings.py
> +]
必要な分だけのがいいかなって思ったけどそっちの方が良いなら合わせます

2024-07-03 07:27 UTC, sora-grayscale commented on PongChat/PongChat/asgi.py
>  )
自分の環境だとerrorになるのでこの下記たかになってます。

2024-07-03 07:37 UTC, sora-grayscale commented on PongChat/pingpong/routing.py
> +    path("ws/chatroom/<chatroom_name>", ChatroomConsumer.as_asgi()),
これは直せそうなので修正だしますます

2024-07-03 08:16 UTC, sora-grayscale commented on PongChat/PongChat/asgi.py
>  )
runserverではなくdaphneで実行して試してみていただけると助かります。
```bash
daphne --settings=PongChat.settings PongChat.asgi:application
```

2024-07-03 08:19 UTC, yuki-shimoda-crypto commented on PongChat/PongChat/asgi.py
>  )
すみません
もともとのやつでいきましょう

2024-07-03 08:20 UTC, yuki-shimoda-crypto approved these changes

2024-07-03 10:49 UTC, Yono1112 approved these changes

2024-07-03 10:49 UTC, merged