75 feat remote play
yuki-shimoda-crypto/42_ft_transcendence pull request #85
Opened 2024-07-02 14:21 UTC by yuki-shimoda-crypto

## コミットの種類

- [x] feat: 新機能や機能の追加
- [ ] fix: バグの修正
- [ ] docs: ドキュメントの変更
- [ ] style: コードスタイルの調整（ロジックの変更は無し）
- [ ] refactor: バグを修正したり機能を追加せずに、コードをリファクタリング
- [ ] test: テストコードの追加や修正
- [ ] chore: ビルドプロセスやツールの変更
- [ ] other: 上記のいずれにも当てはまらないその他の変更

## 以下は、提供された変更に基づくPull Requestのコメントです。

---

## 概要

このPull Requestは、リモートプレイ機能のバグ修正と機能追加を行います。

### 主な変更点

1. **WebSocketのリモートプレイ機能の改善**
   - `GameConsumer` と `GameSessionConsumer` クラスの更新。
   - WebSocket接続の際のユーザー情報の扱いの改善。
   - プレイヤーの位置とスコア更新の非同期処理の修正。

2. **モデルの変更**
   - `Game` モデルに `score_last_update` フィールドを追加し、スコアの更新時間を管理。
   - マイグレーションファイルの更新と追加。

3. **静的ファイルの更新**
   - JavaScriptファイルをリファクタリングし、ボールとパドルの位置や速度の計算を修正。
   - スコア更新やゲーム終了の処理を改善。

4. **テンプレートの更新**
   - 新しいテンプレートファイル `multiplayer_play_remote.html` を追加し、リモートプレイのUIを改善。
   - 一部テンプレートのファイル名を変更し、よりわかりやすい名前に更新。

5. **その他の変更**
   - ロギング設定を追加し、デバッグ情報をコンソールに出力するように変更。
   - Django管理サイトに `Game` モデルを登録。

### テスト

- 変更内容はローカル環境でテスト済みです。
- 特に、リモートプレイ機能が意図した通りに動作することを確認しました。

### クローズするIssue

- close #75

---

このPull Requestは、リモートプレイの安定性と使いやすさを向上させるための重要な修正を含んでいます。レビューとマージをよろしくお願いします。

2024-07-03 11:08 UTC, Yono1112 commented on PongChat/pingpong/consumers.py
> +        )
loggerはこの処理において必須の内容なのでしょうか？

2024-07-03 11:09 UTC, Yono1112 commented on PongChat/pingpong/consumers.py
> +        logger.info("Finalizing the game")
ここもloger入ってる

2024-07-03 11:29 UTC, yuki-shimoda-crypto commented on PongChat/pingpong/consumers.py
> +        logger.info("Finalizing the game")
fixed

2024-07-03 12:43 UTC, sora-grayscale commented
- リモートプレイなのに左右で操作違うのがちょっと分かりづらいかも
- 相手の名前持ってこれるとUI的にわかりやすいかもあと色変えるとか

2024-07-03 12:49 UTC, sora-grayscale commented
8000番(web-prod)の方でremote gameできない？かも

2024-07-03 13:07 UTC, sora-grayscale reviewed
# WebSocket通信の改善案

## 1. 左右の操作の分かりやすさの改善
- 現在の実装では、リモートプレイ時に左右の操作が分かりづらい可能性がある
  - 左右どちらに割り当てられてもw,sとキーボードの上下ボタンどちらもで操作できると良い
- ユーザー名を表示するなどして、プレイヤーの区別を明確にする
- プレイヤーの色を変更するなどして、視覚的な区別を付ける

## 2. ゲーム終了時の挙動の改善
- ゲーム終了後にリロードすると、バグが発生する可能性がある
- ゲーム終了時にクライアントにイベントを送信し、適切な処理を行う
- ゲーム終了後は、ゲームURLへのアクセスを制限する
擬似的なイメージ
```python
def is_allowed_user(user):
    # 特定のユーザーのみアクセス可能な条件を記述
    return user.is_superuser or user.is_staff

@login_required
@user_passes_test(is_allowed_user)
def my_view(request):
    # ビューの処理
    if is_event_ended():
        # イベント終了時の処理
        raise PermissionDenied

def is_event_ended():
    # イベントの終了状態を確認する処理
    return True
```

## 3. 8000番ポートでのリモートゲームの動作確認
- 8000番ポートでリモートゲームが動作しない可能性がある
- ログを確認し、Socketとのコネクションが確立されていないことを確認
- ルーティングの設定を見直し、WebSocket通信が正しく行われるよう修正する

2024-07-04 11:32 UTC, sora-grayscale requested changes
- 自分vs自分ができてしまうからマッチ条件にuserが異なるときを入れたほうが良さそうです。

2024-07-05 07:57 UTC, sora-grayscale approved these changes

2024-07-05 13:09 UTC, Yono1112 commented
> * 自分vs自分ができてしまうからマッチ条件にuserが異なるときを入れたほうが良さそうです。
ごめん、approveしちゃったけど、これは解決してるの？

2024-07-05 14:35 UTC, merged