86 feat tournament
yuki-shimoda-crypto/42_ft_transcendence pull request #94
Opened 2024-07-05 17:35 UTC by yuki-shimoda-crypto

## コミットの種類

- [ ] feat: 新機能や機能の追加
- [ ] fix: バグの修正
- [ ] docs: ドキュメントの変更
- [ ] style: コードスタイルの調整（ロジックの変更は無し）
- [ ] refactor: バグを修正したり機能を追加せずに、コードをリファクタリング
- [ ] test: テストコードの追加や修正
- [ ] chore: ビルドプロセスやツールの変更
- [ ] other: 上記のいずれにも当てはまらないその他の変更

## このプルリクエストの内容

## 変更による影響

## テスト手順

## スクリーンショット

## その他のノート

2024-07-06 09:00 UTC, sora-grayscale commented
mdはdocsにおいたほうがいいかも

2024-07-06 09:20 UTC, sora-grayscale commented
- 試合終了後の表示
   - "Next Match"ではなく、"Check Results"などの表示のほうが適切かもしれない

2024-07-06 09:24 UTC, sora-grayscale requested changes

2024-07-06 09:24 UTC, sora-grayscale commented on PongChat/pingpong/static/pingpong/js/tournament/score.js
> +export const winningScore = 1;
```suggestion
export const winningScore = 11;
```

2024-07-06 09:45 UTC, sora-grayscale approved these changes

2024-07-06 09:49 UTC, sora-grayscale approved these changes

2024-07-07 09:02 UTC, yuki-shimoda-crypto commented on .vscode/launch.json
> +                "0.0.0.0:8000"
```suggestion
            "args": [
                "0.0.0.0:8000"
```suggestion
            "args": [
                "runserver",
                "0.0.0.0:8000"
```
```

2024-07-07 10:08 UTC, Yono1112 approved these changes
良さそう

2024-07-07 10:08 UTC, merged